import type { User, Product, Order } from "./types"

export const mockUsers: User[] = [
  {
    id: "farmer-1",
    email: "jean.dupont@email.com",
    name: "Jean Dupont",
    role: "farmer",
    phone: "+33 6 12 34 56 78",
    location: "Provence-Alpes-Côte d'Azur",
    createdAt: "2024-01-15",
  },
  {
    id: "farmer-2",
    email: "marie.martin@email.com",
    name: "Marie Martin",
    role: "farmer",
    phone: "+33 6 98 76 54 32",
    location: "Bretagne",
    createdAt: "2024-02-20",
  },
  {
    id: "buyer-1",
    email: "pierre.bernard@email.com",
    name: "Pierre Bernard",
    role: "buyer",
    phone: "+33 6 11 22 33 44",
    location: "Paris",
    createdAt: "2024-03-10",
  },
  {
    id: "admin-1",
    email: "admin@agrimarche.fr",
    name: "Administrateur",
    role: "admin",
    createdAt: "2024-01-01",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Tomates Bio",
    description: "Tomates cultivées sans pesticides, variété ancienne coeur de boeuf.",
    category: "legumes",
    price: 4.5,
    unit: "kg",
    quantity: 150,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/fresh-red-tomatoes-on-vine.jpg",
    createdAt: "2024-06-01",
    isAvailable: true,
  },
  {
    id: "prod-2",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Courgettes",
    description: "Courgettes fraîches du jardin, récoltées le matin même.",
    category: "legumes",
    price: 3.2,
    unit: "kg",
    quantity: 80,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/fresh-green-zucchini-vegetables.jpg",
    createdAt: "2024-06-02",
    isAvailable: true,
  },
  {
    id: "prod-3",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Pommes Gala",
    description: "Pommes croquantes et sucrées, parfaites pour les desserts ou à croquer.",
    category: "fruits",
    price: 2.8,
    unit: "kg",
    quantity: 200,
    location: "Bretagne",
    image: "/red-gala-apples-fresh.jpg",
    createdAt: "2024-06-03",
    isAvailable: true,
  },
  {
    id: "prod-4",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Lait Frais",
    description: "Lait entier de vaches élevées en pâturage, non pasteurisé.",
    category: "produits-laitiers",
    price: 1.8,
    unit: "litre",
    quantity: 50,
    location: "Bretagne",
    image: "/fresh-milk-bottle-farm.jpg",
    createdAt: "2024-06-04",
    isAvailable: true,
  },
  {
    id: "prod-5",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Miel de Lavande",
    description: "Miel artisanal récolté dans les champs de lavande de Provence.",
    category: "miel",
    price: 12,
    unit: "pot 500g",
    quantity: 30,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/honey-jar-lavender.jpg",
    createdAt: "2024-06-05",
    isAvailable: true,
  },
  {
    id: "prod-6",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Oeufs Fermiers",
    description: "Oeufs de poules élevées en plein air, calibre gros.",
    category: "oeufs",
    price: 4.5,
    unit: "douzaine",
    quantity: 100,
    location: "Bretagne",
    image: "/farm-fresh-eggs-basket.jpg",
    createdAt: "2024-06-06",
    isAvailable: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    buyerId: "buyer-1",
    buyerName: "Pierre Bernard",
    buyerPhone: "+33 6 11 22 33 44",
    productId: "prod-1",
    productName: "Tomates Bio",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    quantity: 5,
    totalPrice: 22.5,
    status: "confirmed",
    createdAt: "2024-06-10",
  },
  {
    id: "order-2",
    buyerId: "buyer-1",
    buyerName: "Pierre Bernard",
    buyerPhone: "+33 6 11 22 33 44",
    productId: "prod-3",
    productName: "Pommes Gala",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    quantity: 3,
    totalPrice: 8.4,
    status: "pending",
    createdAt: "2024-06-12",
  },
]
