import type { User, Product, Order, Article, Rating } from "./types"

export const mockUsers: User[] = [
  {
    id: "farmer-1",
    email: "jean.dupont@email.com",
    name: "Jean Dupont",
    role: "farmer",
    phone: "+33 6 12 34 56 78",
    location: "Provence-Alpes-Côte d'Azur",
    createdAt: "2024-01-15",
    rating: 4.5,
    reviewCount: 1,
  },
  {
    id: "farmer-2",
    email: "marie.martin@email.com",
    name: "Marie Martin",
    role: "farmer",
    phone: "+33 6 98 76 54 32",
    location: "Bretagne",
    createdAt: "2024-02-20",
    rating: 4.8,
    reviewCount: 2,
  },
  {
    id: "buyer-1",
    email: "pierre.bernard@email.com",
    name: "Pierre Bernard",
    role: "buyer",
    phone: "+33 6 11 22 33 44",
    location: "Paris",
    createdAt: "2024-03-10",
  },
  {
    id: "admin-1",
    email: "admin@agrimarche.fr",
    name: "Administrateur",
    role: "admin",
    createdAt: "2024-01-01",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Tomates Bio",
    description: "Tomates cultivées sans pesticides, variété ancienne coeur de boeuf.",
    category: "legumes",
    price: 4.5,
    unit: "kg",
    quantity: 150,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/fresh-red-tomatoes-on-vine.jpg",
    createdAt: "2024-06-01",
    isAvailable: true,
  },
  {
    id: "prod-2",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Courgettes",
    description: "Courgettes fraîches du jardin, récoltées le matin même.",
    category: "legumes",
    price: 3.2,
    unit: "kg",
    quantity: 80,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/fresh-green-zucchini-vegetables.jpg",
    createdAt: "2024-06-02",
    isAvailable: true,
  },
  {
    id: "prod-3",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Pommes Gala",
    description: "Pommes croquantes et sucrées, parfaites pour les desserts ou à croquer.",
    category: "fruits",
    price: 2.8,
    unit: "kg",
    quantity: 200,
    location: "Bretagne",
    image: "/red-gala-apples-fresh.jpg",
    createdAt: "2024-06-03",
    isAvailable: true,
  },
  {
    id: "prod-4",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Lait Frais",
    description: "Lait entier de vaches élevées en pâturage, non pasteurisé.",
    category: "produits-laitiers",
    price: 1.8,
    unit: "litre",
    quantity: 50,
    location: "Bretagne",
    image: "/fresh-milk-bottle-farm.jpg",
    createdAt: "2024-06-04",
    isAvailable: true,
  },
  {
    id: "prod-5",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    name: "Miel de Lavande",
    description: "Miel artisanal récolté dans les champs de lavande de Provence.",
    category: "miel",
    price: 12,
    unit: "pot 500g",
    quantity: 30,
    location: "Provence-Alpes-Côte d'Azur",
    image: "/honey-jar-lavender.jpg",
    createdAt: "2024-06-05",
    isAvailable: true,
  },
  {
    id: "prod-6",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    name: "Oeufs Fermiers",
    description: "Oeufs de poules élevées en plein air, calibre gros.",
    category: "oeufs",
    price: 4.5,
    unit: "douzaine",
    quantity: 100,
    location: "Bretagne",
    image: "/farm-fresh-eggs-basket.jpg",
    createdAt: "2024-06-06",
    isAvailable: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    buyerId: "buyer-1",
    buyerName: "Pierre Bernard",
    buyerPhone: "+33 6 11 22 33 44",
    productId: "prod-1",
    productName: "Tomates Bio",
    farmerId: "farmer-1",
    farmerName: "Jean Dupont",
    quantity: 5,
    totalPrice: 22.5,
    status: "confirmed",
    createdAt: "2024-06-10",
  },
  {
    id: "order-2",
    buyerId: "buyer-1",
    buyerName: "Pierre Bernard",
    buyerPhone: "+33 6 11 22 33 44",
    productId: "prod-3",
    productName: "Pommes Gala",
    farmerId: "farmer-2",
    farmerName: "Marie Martin",
    quantity: 3,
    totalPrice: 8.4,
    status: "pending",
    createdAt: "2024-06-12",
  },
]

export const mockArticles: Article[] = [
  {
    id: "article-1",
    title: "Comment l'IA transforme nos rendements",
    description: "Découvrez comment l'agriculture de précision aide les agriculteurs à optimiser leurs récoltes.",
    content: "L'intelligence artificielle n'est plus réservée aux entreprises technologiques. Aujourd'hui, elle descend dans les champs. Grâce à des capteurs IoT, des drones et des algorithmes d'analyse d'images satellitaires, les agriculteurs peuvent désormais prédire le meilleur moment pour semer, irriguer et récolter.\n\nUne récente étude montre que l'adoption de ces technologies permettrait d'augmenter les rendements de 15% tout en réduisant l'utilisation d'eau et de pesticides de 20%. Cette transition technologique offre de nouvelles perspectives pour une agriculture à la fois plus rentable et plus respectueuse de l'environnement.",
    category: "agriculteurs",
    imageUrl: "https://images.unsplash.com/photo-1628102491629-778571d893a3?q=80&w=1000",
    authorName: "Jean Dupont",
    createdAt: "2024-06-15",
  },
  {
    id: "article-2",
    title: "Le boom des produits laitiers locaux",
    description: "Les consommateurs se tournent de plus en plus vers le lait et le fromage en circuit court.",
    content: "Au cours des cinq dernières années, la demande pour les produits laitiers issus de circuits courts a explosé. Les consommateurs, de plus en plus soucieux de leur santé et de l'environnement, préfèrent acheter directement auprès des producteurs de leur région.\n\nCe phénomène s'explique par un besoin de transparence et de qualité. Le goût du lait frais, non standardisé par l'industrie de masse, séduit une nouvelle génération d'acheteurs prêts à payer le juste prix pour soutenir l'économie locale. Les fromages artisanaux, riches de leur terroir, regagnent également leurs lettres de noblesse dans les étals de marché.",
    category: "produits",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1000",
    authorName: "Marie Martin",
    createdAt: "2024-06-18",
  },
  {
    id: "article-3",
    title: "Changement climatique : Défis pour l'agriculture mondiale",
    description: "Des températures extrêmes aux précipitations imprévisibles, comment s'adapter ?",
    content: "Le monde agricole est en première ligne face au dérèglement climatique. Les épisodes de sécheresse prolongée, suivis de pluies diluviennes, bouleversent les calendriers de semi et de récolte à travers le globe.\n\nFace à ces défis, l'adaptation est le maître mot. Les chercheurs travaillent sur le développement de nouvelles variétés de semences plus résistantes à la sécheresse et à la chaleur. Parallèlement, les pratiques agroécologiques telles que l'agroforesterie et la couverture végétale des sols gagnent du terrain. Elles permettent de maintenir l'humidité, d'améliorer la biodiversité et de séquestrer plus de carbone, offrant ainsi des solutions durables pour l'avenir de notre alimentation.",
    category: "monde",
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3844?q=80&w=1000",
    authorName: "Administrateur",
    createdAt: "2024-06-20",
  }
]
export const mockRatings: Rating[] = [
  {
    id: "rating-1",
    farmerId: "farmer-1",
    authorId: "buyer-1",
    authorName: "Pierre Bernard",
    stars: 4,
    comment: "Très bons légumes, frais et savoureux.",
    createdAt: "2024-06-15",
  },
  {
    id: "rating-2",
    farmerId: "farmer-2",
    authorId: "buyer-1",
    authorName: "Pierre Bernard",
    stars: 5,
    comment: "Le lait est exceptionnel, je recommande !",
    createdAt: "2024-06-18",
  },
  {
    id: "rating-3",
    farmerId: "farmer-2",
    authorId: "admin-1",
    authorName: "Administrateur",
    stars: 5,
    comment: "Producteur sérieux et régulier.",
    createdAt: "2024-06-20",
  },
]
