import type { User, Product, Order, Article, Rating, Conversation, ChatMessage, ShowcaseProduct } from "./types"

export const mockUsers: User[] = [
  {
    id: "farmer-1",
    email: "Richard@gmail.com",
    name: "Richard DM",
    role: "farmer",
    phone: "0813780615",
    location: "Kasaï",
    createdAt: "2024-01-15",
    rating: 4.5,
    reviewCount: 1,
  },
  {
    id: "farmer-2",
    email: "gerth@gmail.com",
    name: "Gerth KB",
    role: "farmer",
    phone: "0851711233",
    location: "Kinshasa",
    createdAt: "2024-02-20",
    rating: 4.8,
    reviewCount: 2,
  },
  {
    id: "buyer-1",
    email: "roseline@gmail.com",
    name: "Roseline DM",
    role: "buyer",
    phone: "+33 123 33 467 24",
    location: "Kinshasa",
    createdAt: "2024-03-10",
  },
  {
    id: "admin-1",
    email: "ordi@gmail.com",
    name: "Ordi DW",
    role: "admin",
    phone: "0830854244",
    createdAt: "2024-01-01",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    farmerId: "farmer-1",
    farmerName: "Richard DM",
    name: "Tomates Bio",
    description: "Tomates cultivées sans pesticides, variété ancienne coeur de boeuf.",
    category: "legumes",
    price: 4500,
    unit: "kg",
    quantity: 150,
    location: "Kasaï",
    image: "/fresh-red-tomatoes-on-vine.jpg",
    createdAt: "2024-06-01",
    isAvailable: true,
  },
  {
    id: "prod-2",
    farmerId: "farmer-1",
    farmerName: "Richard DM",
    name: "Courgettes",
    description: "Courgettes fraîches du jardin, récoltées le matin même.",
    category: "legumes",
    price: 3200,
    unit: "kg",
    quantity: 80,
    location: "Kasaï",
    image: "/fresh-green-zucchini-vegetables.jpg",
    createdAt: "2024-06-02",
    isAvailable: true,
  },
  {
    id: "prod-3",
    farmerId: "farmer-2",
    farmerName: "Gerth KB",
    name: "Pommes Gala",
    description: "Pommes croquantes et sucrées, parfaites pour les desserts ou à croquer.",
    category: "fruits",
    price: 2800,
    unit: "kg",
    quantity: 200,
    location: "Kinshasa",
    image: "/red-gala-apples-fresh.jpg",
    createdAt: "2024-06-03",
    isAvailable: true,
  },
  {
    id: "prod-4",
    farmerId: "farmer-2",
    farmerName: "Gerth KB",
    name: "Lait Frais",
    description: "Lait entier de vaches élevées en pâturage, non pasteurisé.",
    category: "produits-laitiers",
    price: 1800,
    unit: "litre",
    quantity: 50,
    location: "Kinshasa",
    image: "/fresh-milk-bottle-farm.jpg",
    createdAt: "2024-06-04",
    isAvailable: true,
  },
  {
    id: "prod-5",
    farmerId: "farmer-1",
    farmerName: "Richard DM",
    name: "Miel de Lavande",
    description: "Miel artisanal récolté dans les champs de lavande.",
    category: "miel",
    price: 12000,
    unit: "pot 500g",
    quantity: 30,
    location: "Kasaï",
    image: "/honey-jar-lavender.jpg",
    createdAt: "2024-06-05",
    isAvailable: true,
  },
  {
    id: "prod-6",
    farmerId: "farmer-2",
    farmerName: "Gerth KB",
    name: "Oeufs Fermiers",
    description: "Oeufs de poules élevées en plein air, calibre gros.",
    category: "oeufs",
    price: 4500,
    unit: "douzaine",
    quantity: 100,
    location: "Kinshasa",
    image: "/farm-fresh-eggs-basket.jpg",
    createdAt: "2024-06-06",
    isAvailable: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    buyerId: "buyer-1",
    buyerName: "Roseline DM",
    buyerPhone: "+33 123 33 467 24",
    productId: "prod-1",
    productName: "Tomates Bio",
    farmerId: "farmer-1",
    farmerName: "Richard DM",
    quantity: 5,
    totalPrice: 22500,
    status: "confirmed",
    createdAt: "2024-06-10",
  },
  {
    id: "order-2",
    buyerId: "buyer-1",
    buyerName: "Roseline DM",
    buyerPhone: "+33 123 33 467 24",
    productId: "prod-3",
    productName: "Pommes Gala",
    farmerId: "farmer-2",
    farmerName: "Gerth KB",
    quantity: 3,
    totalPrice: 8400,
    status: "pending",
    createdAt: "2024-06-12",
  },
]

export const mockArticles: Article[] = [
  {
    id: "article-1",
    title: "Comment l'IA transforme nos rendements",
    description: "Découvrez comment l'agriculture de précision aide les agriculteurs à optimiser leurs récoltes.",
    content: "L'intelligence artificielle n'est plus réservée aux entreprises technologiques. Aujourd'hui, elle descend dans les champs. Grâce à des capteurs IoT, des drones et des algorithmes d'analyse d'images satellitaires, les agriculteurs peuvent désormais prédire le meilleur moment pour semer, irriguer et récolter.\n\nUne récente étude montre que l'adoption de ces technologies permettrait d'augmenter les rendements de 15% tout en réduisant l'utilisation d'eau et de pesticides de 20%. Cette transition technologique offre de nouvelles perspectives pour une agriculture à la fois plus rentable et plus respectueuse de l'environnement.",
    category: "agriculteurs",
    imageUrl: "https://images.unsplash.com/photo-1628102491629-778571d893a3?q=80&w=1000",
    authorName: "Richard DM",
    createdAt: "2024-06-15",
  },
  {
    id: "article-2",
    title: "Le boom des produits laitiers locaux",
    description: "Les consommateurs se tournent de plus en plus vers le lait et le fromage en circuit court.",
    content: "Au cours des cinq dernières années, la demande pour les produits laitiers issus de circuits courts a explosé. Les consommateurs, de plus en plus soucieux de leur santé et de l'environnement, préfèrent acheter directement auprès des producteurs de leur région.\n\nCe phénomène s'explique par un besoin de transparence et de qualité. Le goût du lait frais, non standardisé par l'industrie de masse, séduit une nouvelle génération d'acheteurs prêts à payer le juste prix pour soutenir l'économie locale. Les fromages artisanaux, riches de leur terroir, regagnent également leurs lettres de noblesse dans les étals de marché.",
    category: "produits",
    imageUrl: "https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1000",
    authorName: "Gerth KB",
    createdAt: "2024-06-18",
  },
  {
    id: "article-3",
    title: "Changement climatique : Défis pour l'agriculture mondiale",
    description: "Des températures extrêmes aux précipitations imprévisibles, comment s'adapter ?",
    content: "Le monde agricole est en première ligne face au dérèglement climatique. Les épisodes de sécheresse prolongée, suivis de pluies diluviennes, bouleversent les calendriers de semi et de récolte à travers le globe.\n\nFace à ces défis, l'adaptation est le maître mot. Les chercheurs travaillent sur le développement de nouvelles variétés de semences plus résistantes à la sécheresse et à la chaleur. Parallèlement, les pratiques agroécologiques telles que l'agroforesterie et la couverture végétale des sols gagnent du terrain. Elles permettent de maintenir l'humidité, d'améliorer la biodiversité et de séquestrer plus de carbone, offrant ainsi des solutions durables pour l'avenir de notre alimentation.",
    category: "monde",
    imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3844?q=80&w=1000",
    authorName: "Ordi DW",
    createdAt: "2024-06-20",
  }
]
export const mockRatings: Rating[] = [
  {
    id: "rating-1",
    farmerId: "farmer-1",
    authorId: "buyer-1",
    authorName: "Roseline DM",
    stars: 4,
    comment: "Très bons légumes, frais et savoureux.",
    createdAt: "2024-06-15",
  },
  {
    id: "rating-2",
    farmerId: "farmer-2",
    authorId: "buyer-1",
    authorName: "Roseline DM",
    stars: 5,
    comment: "Le lait est exceptionnel, je recommande !",
    createdAt: "2024-06-18",
  },
  {
    id: "rating-3",
    farmerId: "farmer-2",
    authorId: "admin-1",
    authorName: "Ordi DW",
    stars: 5,
    comment: "Producteur sérieux et régulier.",
    createdAt: "2024-06-20",
  },
]

export const mockShowcaseProducts: ShowcaseProduct[] = [
  { id: "showcase-1", name: "Tomates du jardin", category: "Légumes", image: "/fresh-red-tomatoes-on-vine.jpg", createdAt: "2024-06-01" },
  { id: "showcase-2", name: "Pommes Gala", category: "Fruits", image: "/red-gala-apples-fresh.jpg", createdAt: "2024-06-02" },
  { id: "showcase-3", name: "Œufs fermiers", category: "Oeufs", image: "/farm-fresh-eggs-basket.jpg", createdAt: "2024-06-03" },
  { id: "showcase-4", name: "Lait fermier", category: "Produits Laitiers", image: "/fresh-milk-bottle-farm.jpg", createdAt: "2024-06-04" },
  { id: "showcase-5", name: "Miel de lavande", category: "Miel", image: "/honey-jar-lavender.jpg", createdAt: "2024-06-05" },
  { id: "showcase-6", name: "Courgettes vertes", category: "Légumes", image: "/fresh-green-zucchini-vegetables.jpg", createdAt: "2024-06-06" },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participantIds: ["admin-1", "farmer-1"],
    participantNames: ["Ordi DW", "Richard DM"],
    lastMessage: "Bien sûr, je m'en occupe dès que possible.",
    lastMessageAt: "2024-06-24T10:30:00Z",
    unreadCount: 1,
  },
  {
    id: "conv-2",
    participantIds: ["admin-1", "farmer-2"],
    participantNames: ["Ordi DW", "Gerth KB"],
    lastMessage: "Bonjour Gerth, j'ai une question sur vos produits.",
    lastMessageAt: "2024-06-23T15:45:00Z",
    unreadCount: 0,
  },
]

export const mockMessages: ChatMessage[] = [
  {
    id: "msg-1",
    conversationId: "conv-1",
    senderId: "admin-1",
    content: "Bonjour Richard, pourriez-vous mettre à jour vos stocks de tomates ?",
    timestamp: "2024-06-24T09:00:00Z",
    read: true,
  },
  {
    id: "msg-2",
    conversationId: "conv-1",
    senderId: "farmer-1",
    content: "Bien sûr, je m'en occupe dès que possible.",
    timestamp: "2024-06-24T10:30:00Z",
    read: false,
  },
  {
    id: "msg-3",
    conversationId: "conv-2",
    senderId: "admin-1",
    content: "Bonjour Gerth, j'ai une question sur vos produits.",
    timestamp: "2024-06-23T15:45:00Z",
    read: true,
  },
]